--  GWindows test application, generated by GWenerator - ...and reworked!

with GWindows.Application,
     GWindows.Base,
     GWindows.Edit_Boxes,
     GWindows.Message_Boxes,
     GWindows.Windows;

with Dialog_Resource_GUI;

procedure Dialog is
  use Dialog_Resource_GUI;
  use GWindows.Base, GWindows.Edit_Boxes,
      GWindows.Message_Boxes, GWindows.Windows;

  pragma Linker_Options ("-mwindows");

  type Dialog_with_Data is new Dialog_Resource_GUI.Nice_Dialog_Type with record
    state : Boolean;
  end record;

  Dlg_1     : Dialog_with_Data;
  Result    : Integer;
  No_Parent : Window_Type;

begin
  Create_Full_Dialog (Dlg_1, No_Parent);
  Center(Dlg_1);
  Result := GWindows.Application.Show_Dialog (Dlg_1);
end Dialog;
