SUB_PACKAGES = simple drawing mdi ownerdraw activex tasks dialogs mouse controls printing databases dll tcl scintilla contrib

include ../makefile.inc

cleanall:
	make cleanall -C activex
	make cleanall -C svg
	make cleanall -C dll
	make cleanall -C tcl