--  This file contains only automatically generated code.
--  DO NOT MODIFY !
--  Change the `datastore\controls.xml` file instead.
--  Generated by: Control_Generator.

with GNAVI_Window;
with GWindows.Base;

package Control_Creators is

   --  Control: Label

   function Create_Index_1
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Icon

   function Create_Index_2
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Bitmap

   function Create_Index_3
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Meta File

   function Create_Index_4
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Button

   function Create_Index_5
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Default Button

   function Create_Index_6
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Cancel Button

   function Create_Index_7
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Default Cancel Button

   function Create_Index_8
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Check Box

   function Create_Index_9
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Two State Button

   function Create_Index_10
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Radio Button

   function Create_Index_11
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Push Radio Button

   function Create_Index_12
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Three State Box

   function Create_Index_13
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Three State Button

   function Create_Index_14
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Edit Box

   function Create_Index_15
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Multi Line Edit Box

   function Create_Index_16
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Rich Edit Box

   function Create_Index_17
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Scintilla Editor

   function Create_Index_18
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: List Box

   function Create_Index_19
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Multiple Selection List Box

   function Create_Index_20
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Combo Box

   function Create_Index_21
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Drop Down Combo Box

   function Create_Index_22
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Drop Down List Box

   function Create_Index_23
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Group Box

   function Create_Index_24
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Panel

   function Create_Index_25
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Scroll Panel

   function Create_Index_26
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Packing Box

   function Create_Index_27
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: GSize Bar

   function Create_Index_28
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: GDuration

   function Create_Index_29
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: GDuration Edit

   function Create_Index_30
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Drawing Panel

   function Create_Index_31
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

   --  Control: Scroll Bar

   function Create_Index_32
     (Parent      : GWindows.Base.Pointer_To_Base_Window_Class;
      Control_XML : GNAVI_Window.Control_Element)
     return GWindows.Base.Pointer_To_Base_Window_Class;

end Control_Creators;
