--  This file contains only automatically generated code.
--  DO NOT MODIFY !
--  Change the GNAVI item & properties instead.
--  Generated by: GNAVI ICG (Interactive Code Generator).

with GWindows.Application;
with GWindows.Drawing_Objects;

separate (GNAVI_Controls_Window_Package)
procedure On_Create (Window : in out GNAVI_Controls_Window_Type)
is
begin
   Width (Window, 200);
   Set_Standard_Font (Window, GWindows.Drawing_Objects.Default_GUI);
   Dock (Window, GWindows.Base.At_Right);
   On_Create_Handler (Window, Do_Create'Access);
   GWindows.GControls.GSize_Bars.Create (Window.Left_Size_Bar,
      Parent => Window,
      Height => 1,
      Left => 0,
      Location => GWindows.Base.At_Left,
      Text => "Controls",
      Top => 0,
      Width => 20);
   GWindows.GControls.GSize_Bars.Maximum_Size (Window.Left_Size_Bar, 300);
   GWindows.GControls.GSize_Bars.Border (Window.Left_Size_Bar, False);
   GWindows.Panels.Create (Window.Controls_Panel,
      Parent => Window,
      Height => 1,
      Left => 0,
      Top => 0,
      Width => 1);
   GWindows.Panels.Dock (Window.Controls_Panel, GWindows.Base.Fill);
   GWindows.Common_Controls.Create (Window.Controls_List,
      Parent => Window.Controls_Panel,
      Align => GWindows.Common_Controls.Align_Left,
      Arrange => True,
      Height => 10,
      Left => 0,
      Selection => GWindows.Common_Controls.Single,
      Show => True,
      Show_Header => False,
      Sort => GWindows.Common_Controls.No_Sorting,
      Top => 0,
      View => GWindows.Common_Controls.Report_View,
      Width => 10);
   GWindows.Common_Controls.Dock (Window.Controls_List, GWindows.Base.Fill);
   GWindows.Windows.On_Create (GWindows.Windows.Window_Type (Window));
end On_Create;
