--  This file contains only automatically generated code.
--  DO NOT MODIFY !
--  Change the GNAVI item & properties instead.
--  Generated by: GNAVI ICG (Interactive Code Generator).

with GWindows.Application;
with GWindows.Drawing_Objects;

separate (GNAVI_Help_Window_Package)
procedure On_Create (Window : in out GNAVI_Help_Window_Type)
is
begin
   Width (Window, 500);
   Height (Window, 400);
   Set_Standard_Font (Window, GWindows.Drawing_Objects.Default_GUI);
   Text (Window, "GNAVI Help");
   On_Create_Handler (Window, Do_Create'Access);
   On_Close_Handler (Window, Do_Close'Access);
   GWindows.ActiveX.Create (Window.html_browser,
      Parent => Window,
      ProgID => "Shell.Explorer",
      Left => 0,
      Top => 0,
      Width => 1,
      Height => 1);
   GWindows.ActiveX.Dock (Window.html_browser, GWindows.Base.Fill);
   GWindows.Windows.On_Create (GWindows.Windows.Window_Type (Window));
end On_Create;
