-- GWindows Installer
-- (code first generated by GWenerator as a test application)

with GWindows.Windows;            use GWindows.Windows;
with GWindows.Application;

with GW_Install_Resource_GUI;
 use GW_Install_Resource_GUI;

procedure GW_Install is

  pragma Linker_Options ("-mwindows");

  Dlg1      : GW_Install_Resource_GUI.Install_dialog_Type;
  Result    : Integer;
  No_Parent : Window_Type;

begin
  Create_Full_Dialog (Dlg1, No_Parent);
  Center(Dlg1);
  Result := GWindows.Application.Show_Dialog (Dlg1);
end GW_Install;
