-- GWindows Installer
-- (code first generated by GWenerator as a test application)

with GWindows.Buttons;                  use GWindows.Buttons;
with GWindows.Windows;            use GWindows.Windows;
with GWindows.Application;

with GW_Install_Resource_GUI;
 use GW_Install_Resource_GUI;

procedure GW_Install is

  pragma Linker_Options ("-mwindows");

  Main_Dlg  : GW_Install_Resource_GUI.Install_dialog_Type;
  Result    : Integer;
  No_Parent : Window_Type;

begin
  Create_Full_Dialog (Main_Dlg, No_Parent);
  Center(Main_Dlg);
  Main_Dlg.Directory_select_button.Hide;
  Main_Dlg.Directory_select_button_permanent.Show;
  Main_Dlg.ANSI_choice.State(Checked);
  Result := GWindows.Application.Show_Dialog (Main_Dlg);
end GW_Install;
