-- GWindows Installer
-- (code first generated by GWenerator as a test application)

with GW_Install_Resource_GUI;           use GW_Install_Resource_GUI;

with UnZip;

with GWindows.Application;
with GWindows.Base;
with GWindows.Buttons;                  use GWindows.Buttons;
with GWindows.Constants;                use GWindows.Constants;
with GWindows.Message_Boxes;            use GWindows.Message_Boxes;
with GWindows.Windows;                  use GWindows.Windows;

with Ada.Command_Line;                  use Ada.Command_Line;
with Ada.Directories;                   use Ada.Directories;
with Ada.Strings.Unbounded;             use Ada.Strings.Unbounded;

procedure GW_Install is

  pragma Linker_Options ("-mwindows");

  Main_Dlg  : GW_Install_Resource_GUI.Install_dialog_Type;
  Result    : Integer;
  No_Parent : Window_Type;

  Install_dir: Unbounded_String:= To_Unbounded_String("C:\temp");

  procedure Select_directory( dummy : in out GWindows.Base.Base_Window_Type'Class ) is
    pragma Warnings(off, dummy);
  begin
    null;-- !!
  end Select_directory;

  procedure Get_Data ( dummy : in out GWindows.Base.Base_Window_Type'Class ) is
    pragma Warnings(off, dummy);
  begin
    Install_dir:= To_Unbounded_String(Main_Dlg.Directory_edit.Text);
  end Get_Data;

  type Character_mode is (ANSI, UNICODE);
  Mode: Character_mode;
  Proceed: Boolean;

begin
  if Argument_Count > 0 then
    -- Install_dir
    -- /a = ANSI
    -- /u = UNICODE
    -- /c = command line, no GUI, no question: can be used in a batch file
    --
    null; -- !!
  end if;
  loop
    Create_Full_Dialog (Main_Dlg, No_Parent);
    Center(Main_Dlg);
    Small_Icon (Main_Dlg, "AAA_Main_Icon");
    Large_Icon (Main_Dlg, "AAA_Main_Icon");
    Main_Dlg.Directory_select_button.Hide;
    Main_Dlg.Directory_select_button_permanent.Show;
    Main_Dlg.ANSI_choice.State(Checked);
    Main_Dlg.Text(
      Main_Dlg.Text & " version " &
      Version_info.FileVersion
    );
    Main_Dlg.Setup_title.Text(
      Main_Dlg.Setup_title.Text &
      ", version " & Version_info.FileVersion
    );
    Main_Dlg.Directory_edit.Text(To_String(Install_dir));
    On_Destroy_Handler (Main_Dlg, Get_Data'Unrestricted_Access);
    On_Click_Handler (
      Main_Dlg.Directory_select_button_permanent,
      Select_directory'Unrestricted_Access
    );
    Result := GWindows.Application.Show_Dialog (Main_Dlg);
    exit when Result = IDCANCEL;
    if Main_Dlg.ANSI_choice.State = Checked then
      Mode:= ANSI;
    else
      Mode:= UNICODE;
    end if;
    Proceed:= True;
    -- We check: 1) existing version 2) valid directory
    if Exists(To_String(Install_dir) & "\framework\gwindows.ads") then
      -- Conflict
      -- ask !!
      null;
    end if;
    begin
      Create_Path(To_String(Install_dir));
    exception
      when Name_Error =>
        Proceed:= False;
        Message_Box(
          "Invalid directory for GWindows installation",
          "Directory """ &
          To_String(Install_dir) &
          """ cannot be created",
          Icon => Error_Icon
        );
    end;
    if Proceed then
      declare
        mem: constant String:= Current_Directory;
      begin
        Set_Directory(To_String(Install_dir));
        begin
          UnZip.Extract(Command_Name);
        exception
          when others =>
            Message_Box(
            "GWindows installation error",
            "Archive extraction failed",
            Icon => Error_Icon
          );
        end;
        Set_Directory(mem);
      end;
      -- !! unpack
      case Mode is
        -- !! copy ansi or unicode
        when ANSI =>
          null;
        when UNICODE =>
          null;
      end case;
      -- goodbye panel
      exit;
    end if;
  end loop;
end GW_Install;
