--  Generated by             : BindCOM v1.0 Beta
--  Generated on             : 3/12/00 10:11:31 PM
--  Library Name             : GNATCOMLibrary
--  Library Documentation    : GNAT Example Type Library
--  Library Version          : 1.0
--  Library LIBID            : {45F9F480-787C-11D3-821C-52544C1913DE}
--  Elements in Type Library : 3


with Interfaces.C;

with GNATCOM.Create.COM_Interface;
with GNATCOM.Types;
with GNATCOM.GUID;

package GNATExample is

   subtype IGNATMessage is
     GNATCOM.Create.COM_Interface.COM_Interface_Type;
   subtype IGNATStat is
     GNATCOM.Create.COM_Interface.COM_Interface_Type;


   type Pointer_To_IGNATMessage is access all IGNATMessage;
   type Pointer_To_IGNATStat is access all IGNATStat;



   LIBID_GNATCOMLibrary : aliased GNATCOM.Types.GUID :=
     GNATCOM.GUID.To_GUID ("{45F9F480-787C-11D3-821C-52544C1913DE}");


      --  Element Name          : IGNATMessage
      --  Element Documentation : Message dual interface
      --  Element Type          : Dispatch
   
      IID_IGNATMessage : aliased GNATCOM.Types.GUID :=
        GNATCOM.GUID.To_GUID ("{45F9F482-787C-11D3-821C-52544C1913DE}");
   
      type af_IGNATMessage_QueryInterface is access
        function (This   : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  riid   : GNATCOM.Types.Pointer_To_GUID;
                  ppvObj : GNATCOM.Types.Pointer_To_Pointer_To_Void)
        return GNATCOM.Types.HRESULT;
      pragma Convention (StdCall, af_IGNATMessage_QueryInterface);
   
      type af_IGNATMessage_AddRef is access
        function (This : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type)
        return Interfaces.C.unsigned_long;
      pragma Convention (StdCall, af_IGNATMessage_AddRef);
   
      type af_IGNATMessage_Release is access
        function (This : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type)
        return Interfaces.C.unsigned_long;
      pragma Convention (StdCall, af_IGNATMessage_Release);
   
      type af_IGNATMessage_GetTypeInfoCount is access
        function (This    : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  pctinfo : GNATCOM.Types.Pointer_To_unsigned)
        return GNATCOM.Types.HRESULT;
      pragma Convention (StdCall, af_IGNATMessage_GetTypeInfoCount);
   
      type af_IGNATMessage_GetTypeInfo is access
        function (This    : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  itinfo  : Interfaces.C.unsigned;
                  lcid    : Interfaces.C.unsigned_long;
                  pptinfo : GNATCOM.Types.Pointer_To_Pointer_To_Void)
        return GNATCOM.Types.HRESULT;
      pragma Convention (StdCall, af_IGNATMessage_GetTypeInfo);
   
      type af_IGNATMessage_GetIDsOfNames is access
        function (This      : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  riid      : GNATCOM.Types.Pointer_To_GUID;
                  rgszNames : GNATCOM.Types.Pointer_To_Pointer_To_char;
                  cNames    : Interfaces.C.unsigned;
                  lcid      : Interfaces.C.unsigned_long;
                  rgdispid  : GNATCOM.Types.Pointer_To_long)
        return GNATCOM.Types.HRESULT;
      pragma Convention (StdCall, af_IGNATMessage_GetIDsOfNames);
   
      type af_IGNATMessage_Invoke is access
        function (This         : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  dispidMember : Interfaces.C.long;
                  riid         : GNATCOM.Types.Pointer_To_GUID;
                  lcid         : Interfaces.C.unsigned_long;
                  wFlags       : Interfaces.C.unsigned_short;
                  pdispparams  : GNATCOM.Types.Pointer_To_DISPPARAMS;
                  pvarResult   : GNATCOM.Types.Pointer_To_VARIANT;
                  pexcepinfo   : GNATCOM.Types.Pointer_To_EXCEPINFO;
                  puArgErr     : GNATCOM.Types.Pointer_To_unsigned)
        return GNATCOM.Types.HRESULT;
      pragma Convention (StdCall, af_IGNATMessage_Invoke);
   
      type af_IGNATMessage_Beep is access
        function (This : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type)
        return GNATCOM.Types.HRESULT;
      --  Audio Alert
      pragma Convention (StdCall, af_IGNATMessage_Beep);
   
      type af_IGNATMessage_MessageBox is access
        function (This    : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  Message : GNATCOM.Types.BSTR)
        return GNATCOM.Types.HRESULT;
      --  Display Message Box
      pragma Convention (StdCall, af_IGNATMessage_MessageBox);
   
   

      --  Element Name          : IGNATMessage
      --  Element Documentation : Message dual interface
      --  Element Type          : Dispatch
   
      IGNATMessage_Beep       : constant := 1;
      IGNATMessage_MessageBox : constant := 2;
   
   

      --  Element Name          : IGNATStat
      --  Element Documentation : Statistics on object interface
      --  Element Type          : Interface
   
      IID_IGNATStat : aliased GNATCOM.Types.GUID :=
        GNATCOM.GUID.To_GUID ("{45F9F483-787C-11D3-821C-52544C1913DE}");
   
      type af_IGNATStat_QueryInterface is access
        function (This   : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  riid   : GNATCOM.Types.Pointer_To_GUID;
                  ppvObj : GNATCOM.Types.Pointer_To_Pointer_To_Void)
        return GNATCOM.Types.HRESULT;
      pragma Convention (StdCall, af_IGNATStat_QueryInterface);
   
      type af_IGNATStat_AddRef is access
        function (This : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type)
        return Interfaces.C.unsigned_long;
      pragma Convention (StdCall, af_IGNATStat_AddRef);
   
      type af_IGNATStat_Release is access
        function (This : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type)
        return Interfaces.C.unsigned_long;
      pragma Convention (StdCall, af_IGNATStat_Release);
   
      type af_IGNATStat_Calls is access
        function (This          : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  NumberOfTimes : GNATCOM.Types.Pointer_To_int)
        return GNATCOM.Types.HRESULT;
      --  Return number of times methods of the IGNATMessage inertface were called
      pragma Convention (StdCall, af_IGNATStat_Calls);
   
   
      --  Element Name          : GNATCOMClass
      --  Element Documentation : GNAT Example Class
      --  Element Type          : CoClass
   
      CLSID_GNATCOMClass : aliased GNATCOM.Types.GUID :=
        GNATCOM.GUID.To_GUID ("{45F9F481-787C-11D3-821C-52544C1913DE}");
   


end GNATExample;
