--  Generated by             : BindCOM v1.0 Beta
--  Generated on             : 2/21/00 2:27:05 PM
--  Library Name             : VBtoAdaLibrary
--  Library Documentation    : VBtoAda Library
--  Library Version          : 1.0
--  Library LIBID            : {3B5A3CE0-E893-11D3-938D-0080C88637DE}
--  Elements in Type Library : 2


with Interfaces.C;

with GNATCOM.Create.COM_Interface;
with GNATCOM.Types;
with GNATCOM.GUID;

package vbtoada is

   subtype IVBtoAda is
     GNATCOM.Create.COM_Interface.COM_Interface_Type;


   type Pointer_To_IVBtoAda is access all IVBtoAda;



   LIBID_VBtoAdaLibrary : aliased GNATCOM.Types.GUID :=
     GNATCOM.GUID.To_GUID ("{3B5A3CE0-E893-11D3-938D-0080C88637DE}");


      --  Element Name          : IVBtoAda
      --  Element Documentation : IVBtoAda Interface
      --  Element Type          : Interface
   
      IID_IVBtoAda : aliased GNATCOM.Types.GUID :=
        GNATCOM.GUID.To_GUID ("{3B5A3CE2-E893-11D3-938D-0080C88637DE}");
   
      type af_IVBtoAda_QueryInterface is access
        function (This   : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  riid   : GNATCOM.Types.Pointer_To_GUID;
                  ppvObj : GNATCOM.Types.Pointer_To_Pointer_To_Void)
        return GNATCOM.Types.HRESULT;
      pragma Convention (StdCall, af_IVBtoAda_QueryInterface);
   
      type af_IVBtoAda_AddRef is access
        function (This : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type)
        return Interfaces.C.unsigned_long;
      pragma Convention (StdCall, af_IVBtoAda_AddRef);
   
      type af_IVBtoAda_Release is access
        function (This : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type)
        return Interfaces.C.unsigned_long;
      pragma Convention (StdCall, af_IVBtoAda_Release);
   
      type af_IVBtoAda_Display is access
        function (This    : access
                    GNATCOM.Create.COM_Interface.COM_Interface_Type;
                  Message : GNATCOM.Types.BSTR)
        return GNATCOM.Types.HRESULT;
      --  Display Message
      pragma Convention (StdCall, af_IVBtoAda_Display);
   
   
      --  Element Name          : VBtoAdaClass
      --  Element Documentation : VBtoAda Class
      --  Element Type          : CoClass
   
      CLSID_VBtoAdaClass : aliased GNATCOM.Types.GUID :=
        GNATCOM.GUID.To_GUID ("{3B5A3CE1-E893-11D3-938D-0080C88637DE}");
   


end vbtoada;
