PACKAGES = task_windows thread_test task_dialogs

ADAOPTS = -I../../framework/

include ../../makefile.inc

task_windows:
	gnatmake ${ADAOPTS} task_windows ${POSTOPTS}

thread_test:
	gnatmake ${ADAOPTS} thread_test ${POSTOPTS}

task_dialogs:
	gnatmake ${ADAOPTS} task_dialogs ${POSTOPTS}