#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define GWen_properties                         105
#define Listen_32x32                            107
#define Ada_file                                116
#define Exe_file                                118
#define Wheels_32x32                            120
#define Less_Horizontal                         122
#define More_Horizontal                         123
#define Less_Vertical                           124
#define More_Vertical                           125
#define Warning_icon                            127
#define Arrow_icon                              129
#define Ada_file_icon                           1000
#define Listen_RC                               1000
#define URL                                     1000
#define Exe_file_icon                           1001
#define GNAT_Version                            1001
#define Initialize_controls                     1001
#define Details_frame                           1002
#define GWen_ver                                1002
#define Separate_items                          1002
#define Ada_cmd                                 1003
#define Ada_comp_label                          1003
#define Basx                                    1004
#define RC_gramm_ver                            1004
#define Basy                                    1005
#define Show_Ada_build                          1005
#define Ear_RC                                  1006
#define Ear_Ada                                 1007
#define RC_Compiler_list                        1007
#define Auto_build_lift_msg                     1008
#define Auto_build_lift_ico                     1010
#define Ada_blue_3                              1011
#define More_less_details                       1012
#define About_box                               1033
#define Not_Listen_32x32                        1033
#define RC_file                                 1034
#define gwenerator_icon                         1035
#define GNAT_URL                                1036
#define GNAVI_URL                               1037
#define ResEdit_URL                             1038
#define Main_Menu                               4108
#define Main_dialog                             4108
#define GNATMake_messages                       4109
#define RC_to_GWindows_messages                 4110
#define Button_Translate                        4112
#define Button_Build                            4114
#define Bar_RC                                  4121
#define Bar_Ada                                 4122
#define Edit_RC_File_Name                       4122
#define Button_Run                              40000
#define New_GWen                                40000
#define Open_GWen                               40001
#define Save_GWen                               40002
#define GWen_Options                            40003
#define GWenerator_Preferences                  40004
#define About                                   40005
#define Show_Details                            40005
#define Newer_RC                                40006
#define Quit                                    40006
#define Save_GWen_as                            40007
#define Generate_test_app                       40008
#define Listen_Ada                              40008
#define Newer_Ada                               40008
#define Auto_translate                          40009
#define Compile_resource_only                   40009
#define Auto_build                              40010
#define Start_main_app                          40010
#define Edit_Main_Ada_File_Name                 40011
#define Button_Browse_Ada                       40012
#define Button_Browse_RC                        40013
#define Use_base_defs                           40015
#define More_less_build                         40016
