--  This file contains only automatically generated code.
--  DO NOT MODIFY !
--  Change the GNAVI item & properties instead.
--  Generated by: GNAVI ICG (Interactive Code Generator).

with GWindows.Application;
with GWindows.Drawing_Objects;

separate (@_Window_Name_@_Package)
procedure On_Create (Window : in out @_Window_Name_@_Type)
is
begin
