PACKAGES = tutorial1 tutorial2 tutorial3 tutorial4 tutorial5 tutorial6 tutorial7 tutorial8 tutorial9 tutorial10 tutorial11 tutorial12 tutorial13 tutorial14 tutorial15 tutorial16 tutorial17 tutorial18 tutorial19 tutorial20 tutorial21

ADAOPTS = -I../framework/

include ../makefile.inc

tutorial1:
	gnatmake ${ADAOPTS} tutorial1 ${POSTOPTS}

tutorial2:
	gnatmake ${ADAOPTS} tutorial2 ${POSTOPTS}

tutorial3:
	gnatmake ${ADAOPTS} tutorial3 ${POSTOPTS}

tutorial4:
	gnatmake ${ADAOPTS} tutorial4 ${POSTOPTS}

tutorial5:
	gnatmake ${ADAOPTS} tutorial5 ${POSTOPTS}

tutorial6:
	gnatmake ${ADAOPTS} tutorial6 ${POSTOPTS}

tutorial7:
	gnatmake ${ADAOPTS} tutorial7 ${POSTOPTS}

tutorial8:
	gnatmake ${ADAOPTS} tutorial8 ${POSTOPTS}

tutorial9:
	gnatmake ${ADAOPTS} tutorial9 ${POSTOPTS}

tutorial10:
	gnatmake ${ADAOPTS} tutorial10 ${POSTOPTS}

tutorial11:
	gnatmake ${ADAOPTS} tutorial11 ${POSTOPTS}

tutorial12:
	gnatmake ${ADAOPTS} tutorial12 ${POSTOPTS}

tutorial13:
	gnatmake ${ADAOPTS} tutorial13 ${POSTOPTS}

tutorial14:
	gnatmake ${ADAOPTS} tutorial14 ${POSTOPTS}

tutorial15:
	gnatmake ${ADAOPTS} tutorial15 ${POSTOPTS}

tutorial16:
	gnatmake ${ADAOPTS} tutorial16 ${POSTOPTS}

tutorial17:
	gnatmake ${ADAOPTS} tutorial17 ${POSTOPTS}

tutorial18:
	gnatmake ${ADAOPTS} tutorial18 ${POSTOPTS}

tutorial19:
	gnatmake ${ADAOPTS} tutorial19 ${POSTOPTS}

tutorial20:
	gnatmake ${ADAOPTS} tutorial20 ${POSTOPTS}

tutorial21:
	gnatmake ${ADAOPTS} tutorial21 ${POSTOPTS}

tutorial22:
	gnatmake ${ADAOPTS} tutorial22 ${POSTOPTS}

tutorial23:
	gnatmake ${ADAOPTS} tutorial23 ${POSTOPTS}
