--  Generated by             : BindCOM v1.0 Beta
--  Generated on             : 2/17/00 11:37:10 AM
--  Library Name             : BeepLibrary
--  Library Documentation    : Beep Type Library
--  Library Version          : 1.0
--  Library LIBID            : {0FE0EE20-8AA2-11D2-81AA-444553540001}
--  Elements in Type Library : 2

with Interfaces.C;

with GNATCOM.Create.COM_Interface;
with GNATCOM.Types;
with GNATCOM.GUID;

package beep is

   subtype IBeep is
     GNATCOM.Create.COM_Interface.COM_Interface_Type;

   type Pointer_To_IBeep is access all IBeep;


   LIBID_BeepLibrary : aliased GNATCOM.Types.GUID :=
     GNATCOM.GUID.To_GUID ("{0FE0EE20-8AA2-11D2-81AA-444553540001}");
   
   
   --  Element Name          : IBeep
   --  Element Documentation : Beep Interface
   --  Element Type          : Dispatch
   
   IID_IBeep : aliased GNATCOM.Types.GUID :=
     GNATCOM.GUID.To_GUID ("{0FE0EE22-8AA2-11D2-81AA-444553540001}");
   
   type af_IBeep_QueryInterface is access
     function (This   : access
                 GNATCOM.Create.COM_Interface.COM_Interface_Type;
               riid   : GNATCOM.Types.Pointer_To_GUID;
               ppvObj : GNATCOM.Types.Pointer_To_Pointer_To_Void)
     return GNATCOM.Types.HRESULT;
   pragma Convention (StdCall, af_IBeep_QueryInterface);
   
   type af_IBeep_AddRef is access
     function (This : access
                 GNATCOM.Create.COM_Interface.COM_Interface_Type)
     return Interfaces.C.unsigned_long;
   pragma Convention (StdCall, af_IBeep_AddRef);
   
   type af_IBeep_Release is access
     function (This : access
                 GNATCOM.Create.COM_Interface.COM_Interface_Type)
     return Interfaces.C.unsigned_long;
   pragma Convention (StdCall, af_IBeep_Release);
   
   type af_IBeep_GetTypeInfoCount is access
     function (This    : access
                 GNATCOM.Create.COM_Interface.COM_Interface_Type;
               pctinfo : GNATCOM.Types.Pointer_To_unsigned)
     return GNATCOM.Types.HRESULT;
   pragma Convention (StdCall, af_IBeep_GetTypeInfoCount);
   
   type af_IBeep_GetTypeInfo is access
     function (This    : access
                 GNATCOM.Create.COM_Interface.COM_Interface_Type;
               itinfo  : Interfaces.C.unsigned;
               lcid    : Interfaces.C.unsigned_long;
               pptinfo : GNATCOM.Types.Pointer_To_Pointer_To_Void)
     return GNATCOM.Types.HRESULT;
   pragma Convention (StdCall, af_IBeep_GetTypeInfo);
   
   type af_IBeep_GetIDsOfNames is access
     function (This      : access
                 GNATCOM.Create.COM_Interface.COM_Interface_Type;
               riid      : GNATCOM.Types.Pointer_To_GUID;
               rgszNames : GNATCOM.Types.Pointer_To_Pointer_To_char;
               cNames    : Interfaces.C.unsigned;
               lcid      : Interfaces.C.unsigned_long;
               rgdispid  : GNATCOM.Types.Pointer_To_long)
     return GNATCOM.Types.HRESULT;
   pragma Convention (StdCall, af_IBeep_GetIDsOfNames);
   
   type af_IBeep_Invoke is access
     function (This         : access
                 GNATCOM.Create.COM_Interface.COM_Interface_Type;
               dispidMember : Interfaces.C.long;
               riid         : GNATCOM.Types.Pointer_To_GUID;
               lcid         : Interfaces.C.unsigned_long;
               wFlags       : Interfaces.C.unsigned_short;
               pdispparams  : GNATCOM.Types.Pointer_To_DISPPARAMS;
               pvarResult   : GNATCOM.Types.Pointer_To_VARIANT;
               pexcepinfo   : GNATCOM.Types.Pointer_To_EXCEPINFO;
               puArgErr     : GNATCOM.Types.Pointer_To_unsigned)
     return GNATCOM.Types.HRESULT;
   pragma Convention (StdCall, af_IBeep_Invoke);
   
   type af_IBeep_Beep is access
     function (This : access
                 GNATCOM.Create.COM_Interface.COM_Interface_Type)
     return GNATCOM.Types.HRESULT;
   --  Make a beep
   pragma Convention (StdCall, af_IBeep_Beep);
   
   
   --  Element Name          : IBeep
   --  Element Documentation : Beep Interface
   --  Element Type          : Dispatch
   
   IBeep_Beep : constant := 1;
   
   --  Element Name          : BeepClass
   --  Element Documentation : Beep Class
   --  Element Type          : CoClass
   
   CLSID_BeepClass : aliased GNATCOM.Types.GUID :=
     GNATCOM.GUID.To_GUID ("{0FE0EE21-8AA2-11D2-81AA-444553540001}");
   
end beep;
