#define IDALL                           3
#define IDCOPY                          4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DATAFITYPE                  129
#define IDD_DATAFINDERDLG               130
#define IDD_AENDERNDLG                  131
#define IDD_CMPFILEDLG                  132
#define IDD_FINDSAMEDLG                 134
#define IDD_ANSCIIANSIDLG               135
#define IDD_TEXT_SUCHEN                 136
#define IDD_MAINVIEW                    137
#define IDB_BITMAP2                     139
#define IDD_FRAGE                       140
#define ID_INFO                         140
#define IDD_COPY                        141
#define IDB_OPEN                        141
#define IDD_PROGRESSDLG                 142
#define IDD_LFCRCONVERT                 143
#define IDD_CMPPATHDLG                  144
#define IDD_ZIPDLG                      145
#define IDD_HEX_SUCHEN                  155
#define IDD_TABCONVERT                  157
#define IDD_RENAMEDLG                   158
#define IDD_ABOUTBOX1                   159
#define IDD_INFOBOX                     159
#define IDB_BANNER          200
#define IDI_ACTIVE2                     213
#define IDI_PRINTER                     222
#define IDIMMER                         1000
#define IDC_COMBO1                      1000
#define IDC_COMBO2                      1001
#define IDNIE                           1002
#define IDC_COMBO3                      1002
#define IDC_FILE1                       1002
#define IDC_DATEI1                      1003
#define IDC_FILE2                       1003
#define IDC_COMBO4                      1003
#define IDC_POS                         1004
#define IDC_DATEI2                      1005
#define IDC_BYTE1                       1005
#define IDC_INFO1                       1006
#define IDC_HEX1                        1006
#define IDC_INFO2                       1007
#define IDC_VON                         1007
#define IDC_BYTE2                       1007
#define IDC_NACH                        1008
#define IDC_HEX2                        1008
#define IDC_DELETE1                     1008
#define IDC_STATIC1                     1009
#define IDC_ANZ                         1009
#define IDC_DELETE2                     1009
#define IDC_STATIC2                     1010
#define IDC_PATHNAME                    1010
#define IDGNORE                         1011
#define IDC_ICON2                       1012
#define IDC_ICON1                       1013
#define IDC_FEHLER                      1014
#define IDC_ICONWND                     1014
#define IDC_PATH1                       1015
#define IDC_PATH2                       1016
#define IDC_RADIO3                      1016
#define IDC_TITLE                       1017
#define IDC_RADIO6                      1018
#define IDC_PROGRESS1                   1019
#define IDC_RADIO7                      1019
#define IDC_RADIO8                      1020
#define IDC_TEXT                        1034
#define IDC_CHECK1                      1043
#define IDC_CHECK2                      1044
#define IDC_CHECK3                      1045
#define IDC_CHECK4                      1046
#define IDC_RADIO1                      1047
#define IDC_RADIO2                      1048
#define IDC_BUTTON1                     1050
#define IDC_RADIO5                      1050
#define IDC_RADIO4                      1051
#define IDC_EDIT1                       1055
#define IDC_EDIT3                       1057
#define IDC_EDIT2                       1075
#define IDC_BUTTON2                     1076
#define IDC_EING1                       1087
#define IDC_EING2                       1088
#define IDC_EING3                       1089
#define IDC_EING4                       1090
#define IDC_EING5                       1091
#define IDC_EING6                       1092
#define IDC_VAR1                        1093
#define IDC_VAR2                        1094
#define IDC_VAR3                        1095
#define IDC_VAR4                        1096
#define IDC_CHECK5                      1097
#define IDC_CHECK6                      1098
#define IDC_LIST1                       1099
#define IDC_GRUPPE1                     1100
#define IDC_GRUPPE2                     1101
#define IDC_GRUPPE3                     1102
#define IDC_GRUPPE4                     1103
#define IDC_GRUPPE5                     1104
#define IDC_EING7                       1124
#define IDC_CHECK7                      1125
#define IDC_CHECK8                      1126
#define ID_DSPIC           5001
#define ID_ADDFILES                     32771
#define ID_FINDTEXT                     32772
#define ID_FINDHEX                      32774
#define ID_AENDERN                      32775
#define ID_INSERTALLFILES               32776
#define ID_COMPAREFILES                 32779
#define ID_DELETALLFILES                32781
#define ID_TABCONVERT                   32782
#define ID_FINDSAME                     32783
#define ID_RELOAD                       32784
#define ID_ASCIIANSI                    32786
#define ID_CONFIGTOOLS                  32787
#define ID_RENAMEFILES                  32788
#define ID_LFCRCONVERT                  32789
#define ID_COMPARETEXT                  32791
#define ID_CMPDIRECTORY                 32792
#define ID_ZIPFILES                     32793
#define ID_STATUS_BAR_FLAT              32794
#define ID_CPPBEATIFY                   32795
#define IDI_ID3                         32796
#define IDI_CYGWIN                      32797