//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Backup.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BACKUPTYPE                  129
#define IDB_DRAGEINS                    130
#define IDB_BILDREG                     133
#define IDD_ZEITPLAN                    134
#define IDI_ICON1                       135
#define IDI_INFO                        135
#define IDD_INFO                        135
#define IDC_CURSORCOPY                  136
#define IDC_CURSORMOVE                  137
#define IDD_DLGVIEW                     137
#define IDB_DRAGDREI                    138
#define IDI_WARNUNG                     140
#define IDD_FRAGE                       140
#define IDD_COPY                        141
#define IDD_PROGRESSDLG                 142
#define IDD_SYNTAXDLG                   143
#define IDIMMER                         1000
#define IDC_EDIT1                       1001
#define IDNIE                           1002
#define IDC_DATEI1                      1003
#define IDC_DATEI2                      1005
#define IDC_INFO1                       1006
#define IDC_RADIO1                      1007
#define IDC_INFO2                       1007
#define IDC_RADIO2                      1008
#define IDC_STATIC1                     1009
#define IDC_RADIO3                      1009
#define IDC_RADIO4                      1010
#define IDC_CHECK1                      1011
#define IDC_LETZTES                     1012
#define IDC_ICON2                       1012
#define IDC_ICON1                       1013
#define IDC_FEHLER                      1014
#define IDC_ZIEL                        1015
#define IDC_CHECK2                      1016
#define IDC_STATIC2                     1017
#define IDC_VON                         1018
#define IDC_NACH                        1019
#define IDC_QUELLE                      1020
#define IDC_PROZENT                     1021
#define IDC_PROGRESS1                   1022
#define IDC_TEXT1                       1023
#define IDC_TEXT2                       1024
#define IDC_TEXT3                       1025
#define IDC_CHECK3                      1028
#define ID_SELECTALL                    32772
#define ID_EINFUEGEN                    32776
#define ID_ZEITPLAN                     32777
#define ID_BACKUP                       32778
#define ID_APP_INFO                     32779
#define ID_PATHUP                       32780
#define ID_REGON                        32781
#define ID_CONFIG                       32783
#define ID_ITEMUP                       32784
#define ID_ITEMDOWN                     32785
#define ID_NEWENTRY                     32786
#define ID_SYNTAXINFO                   32787
#define ID_SETCPP                       32788
#define ID_STATUS_BAR_FLAT              32789